### ISSUE TITLE
Wrong data type when running "./PROGRAMMES/GONE"

### ISSUE THREAD

**Issue by QianXiaobo** [esrud/GONE#2]
Hello everyone,
I am trying to run GONE with ~2M SNPs from 22 chromosomes for 45 individuals. 
I used script like this `./PROGRAMMES/GONEparallel.sh -hc $hc outfileLD $REPS 8`
but I got error as following:
```
Running GONE
 Wrong data type. Probably some input values are out of range. Wrong data type. Probably some input values are out of range. Wrong data type. Probably some input values are out of range.


 Wrong data type. Probably some input values are out of range. Wrong data type. Probably some input values are out of range.
 Wrong data type. Probably some input values are out of range.

 Wrong data type. Probably some input values are out of range.
 Wrong data type. Probably some input values are out of range.
 Wrong data type. Probably some input values are out of range.
 Wrong data type. Probably some input values are out of range.
 Wrong data type. Probably some input values are out of range.
 Wrong data type. Probably some input values are out of range.
 Wrong data type. Probably some input values are out of range.
 Wrong data type. Probably some input values are out of range.
 Wrong data type. Probably some input values are out of range.
 Wrong data type. Probably some input values are out of range.
 Wrong data type. Probably some input values are out of range.
 Wrong data type. Probably some input values are out of range.
 Wrong data type. Probably some input values are out of range.
 Wrong data type. Probably some input values are out of range.
```
I guessed there must be some wrong with input file. So I checked my **outfileLD** file and just gave you first ten lines:
```
INPUT FOR GONE



1       Phase (0: pseudohaploids; 1: known phase; 2: unknown phase)
7.891860       sample size (individuals; corrected for zeroes)
-0.007379       Hardy-Weinberg deviation
-16818877366 0.000000 0.050903 2
24985704633 0.182761 0.050938 4
7035894977 0.102980 0.051170 6
```
I am confused about **sample size** , it should have been 45 but here is 7.891860.
So my questions are:
1. Does the outfileLD file cause the "Wrong data type" error of GONE?
2. Why "sample size" in the outfileLD is not equal to the real value?
3. If the "sample size" is wrong, does that mean the other values in different lines are wrong? If sample size issue doesn't impact on the other values, I can just correct the value of sample size myself and keep on running GONE.

This is **INPUT_PARAMETERS_FILE** if it is necessary for you.
```
#INPUT_PARAMETERS_FILE

########################################################

PHASE=1 ### Phase = 0 (pseudohaploids), 1 (known phase), 2 (unknown phase)
cMMb=0  ### CentiMorgans per Megabase (if distance is not available). For humans set cMMb=0 and distances are obtained from genetic data file
DIST=1  ### none (0), Haldane correction (1) or Kosambi correction (2)
NGEN=2000 ### Number of generations for which linkage data is obtained in bins
NBIN=400  ### Number of bins (e.g. 1000, so that each bin includes NGEN/NBIN generations)
MAF=0.0   ### Minimum allele frequency (0-1)
ZERO=1    ### 0: Remove SNPs with zeroes (1: allow for them)
maxNCHROM=-99  ### Maximum number of chromosomes to be analysed (-99 = all chromosomes; maximum number is 200)
maxNSNP=100000 ### Maximum approx number of SNPs per chromosomes to be analysed (max is 100000)
hc=0.05   ### Maximum value of c analysed
REPS=20   ### Number of replicates to RUN GONE
threads=16  ### Number of threads (if -99 it uses all possible processors)

###################################################################
```
Best wishes, 
Thank you very much!

**Comment by armando-caballero** [comment]
Dear QianXiaobo,

I can see that the line
-16818877366 0.000000 0.050903 2
has a problem. First, there is a negative number of pairs, so this means that some lack of memory or space has occurred. The 0.000000 should be also a non-zero number.
The line
7.891860       sample size (individuals; corrected for zeroes)
seems to indicate that the number of ungenotyped SNPs is very large. Is that the case?
The sample is 45 but the effective sample size (considering all zeros -ungenotyped SNPs-) is much smaller.
This means that if, for example, one individual has only half of the SNPs genotyped, it counts as half an individual.

Please try with a smaller number of SNPs per chromosome in order to see what is the problem, e.g.
maxNSNP=20000 ### Maximum approx number of SNPs per chromosomes to be analysed (max is 100000)
If that works then go to 50000.

I assume your .map file has the column of genetic distances (the middle column) filled with the distances in cM, as you marked cMMb=0. Correct?
Armando.

**Comment by armando-caballero** [comment]
Dear QianXiaobo,

I think I have realised what the problem may be. The option cMMb=0 for human data was removed in our latest version because it involved using PLINK, or other external program, but we forgot to note that in the INPUT_PARAMETERS_FILE and the SCRIPT ESTIMATION Ne PROCEDURE.docx (this is now fixed an a note of modification is given). Sorry about that.

Then, if your .map file has zeroes in your genetic distance column (third column), then you have to set up a cMMb different from zero in the INPUT_PARAMETERS_FILE, say cMMb=1.2 for humans. Alternatively, you may include your genetic map in the .map file and then the program will use those distances irrespective of the value cMMb you inserted in the  INPUT_PARAMETERS_FILE.

To insert the genetic map in you .map file you may use the option --cm-map of PLINK.

Armando.

**Comment by QianXiaobo** [comment]
@armando-caballero Thank you very much! I think I know what is going wrong.
You are right that people should try with a small number of SNPs per chromosome and repeat it instead of setting larger maxNSNP, so I set maxNSNP=10000 and it works!
- And about sample size which is not equal to its real value,  I think it is because of ungenotyped SNPs existing as you mentioned. Actually, I do filter out SNPs with 10% missing among 45 individuals using PLINK before GONE. And if I use a large maxNSNP, lots of ungenotyped SNPs will be selected too and I think it is not suitable. Now I try with maxNSNP=10000, the sample size is correct in each chromosome!
- About genetic distance in .map file, I generated this .map file with PLINK --cm-map before this issue and set cMMb=0. When I set maxNSNP=10000 (or smaller one than 100000) and keep other parameters, GONE works, so I think it doesn't matter.
Back to the second sentence, if I use a smaller maxNSNP and repeat this command several time, I will get several results like following, how can I implement these results? For each generation, $$\Sigma(Geometric_mean)/n$$, is it correct?


**Output_Ne**
```
Ne averages over 20 independent estimates.
Generation      Geometric_mean
1       42.1623
2       42.1623
3       42.1623
4       42.1623
5       35885.9
```
**Output_d2**
```
Sample d2 values. Average (d2obs-d2prd)^2 = 3.24962e-07
rec.rate_c      observed_d2     adjusted_d2
0.041127        0.051415        0.0498905
0.02899 0.05231 0.0524097
0.022408        0.053588        0.0540048
0.018278        0.054693        0.0552005
0.015447        0.055803        0.0561847
0.013377        0.056203        0.0570401
```

**Comment by armando-caballero** [comment]
Good. You could be better run it with more SNPs, say 20000 to 50000. It is also better if you make 40 replicates of GONE instead of 20 to reach an optimal solution: REPS=40   ### Number of replicates to RUN GONE.
Each run you make will give the predicted Ne each generation with a given sample of SNPs (we provide the geometric mean over GONE replicates as we found it is what works better). Everytime you run the program again it will use a different sample of SNPs, so you can use these runs as "replicates", and get an standard error from them.
Is the large drop 5 generations ago a result you would expect or anticipate? 
Armando.

**Comment by QianXiaobo** [comment]
@armando-caballero Thanks for your suggestion and I will try REPS=40.
This afternoon I tried maxNSNP=50000 and it is still running, I guess it will take more time.
Actually, I am not sure about my result because I am a new researcher in this field. I think the values of the first five generations are too small which looks depending on my sampling individuls(45 individuals). And referring to the history of this ethnic group, I don't think such a large drop is expected.
XB.

**Comment by OKersten** [comment]
Hi,

I am encountering the same error message ` Wrong data type. Probably some input values are out of range`

I pinpointed it to the fact that the outfileLD has -99 instead of 6 (sample size).
I have 6 individuals, 24 chromosomes, and a total of ca. 8M SNPs.
There is a few other things that don't seem to work as they should. 

a) in the OUTPUT_* file, the total NSNPs is 2M. I don't have any monomorphic or missing SNPs though, so shouldn't it be 8M?
b) Chr 3-24 seem to work fine. Only 1 + 2 have strange sample sizes.
c) The corrected sample size in OUTPUT_* is negative for the troublesome chromosomes (1+2), whereas 6 for the rest (that is what it should be as I don't have monomorphic or missingness). I guess this is the reason for why b) is happening.
d) the first few lines of outfileLD* of some of the "working" chromosomes start as follows
```
2
6.000000
-0.120489
0 0 0 2 0 0
0 0 0 4 0 0
0 0 0 6 0 0
0 0 0 8 0 0
0 0 0 10 0 0
437780 0.034013 0.143440 15 0.003518 0.024526
```
Is it "normal" to have lines begin with 3 zeros?

I attached all files to potentially recreate the issue (name of pop is SPI). Except for the .map and .ped as they are too big too attach to this post,

Thanks for any help!

[INPUT_PARAMETERS_FILE.txt](https://github.com/esrud/GONE/files/8476546/INPUT_PARAMETERS_FILE.txt)
[outfileLD1.txt](https://github.com/esrud/GONE/files/8476547/outfileLD1.txt)
[outfileLD7.txt](https://github.com/esrud/GONE/files/8476548/outfileLD7.txt)
[outfileLD24.txt](https://github.com/esrud/GONE/files/8476549/outfileLD24.txt)
[OUTPUT_SPI.txt](https://github.com/esrud/GONE/files/8476550/OUTPUT_SPI.txt)
