### ISSUE TITLE
"Format error in file outfileLD" when running GONE

### ISSUE THREAD

**Issue by andrewSharo** [esrud/GONE#31]
Hi Armando,

Thanks for creating GONE! I have run it successfully a few times, but recently have run into the following error:

```bash script_GONE.sh all60GenMapGPCFixed
DIVIDE .ped AND .map FILES IN CHROMOSOMES
RUNNING ANALYSIS OF CHROMOSOMES ...
CHROMOSOME ANALYSES took 6 seconds
Running GONE
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
  Error opening file outfileLD_TEMP/outfileLD_1_GONE_Nebest
 END OF ALL PROCESSES
GONE run took 0 seconds
END OF ANALYSES
mv: cannot stat 'outfileLD_Ne_estimates': No such file or directory
mv: cannot stat 'outfileLD_d2_sample': No such file or directory
```

I looked through some of the previous issues that give this error, and I don't think this is a zeros issue or an issue with too many snps.  I'm attaching my ped and map file. If you could take a look I'd be really grateful.

Andrew
[all60GenMapGPCFixed_map.zip](https://github.com/esrud/GONE/files/14205700/all60GenMapGPCFixed_map.zip)
[all60GenMapGPCFixed_ped.zip](https://github.com/esrud/GONE/files/14205707/all60GenMapGPCFixed_ped.zip)

**Comment by armando-caballero** [comment]
Dear Andrew,
At a quick look I see that some of your "chromosomes" (I guess scaffolds) have very few SNPs, even just a single one (73) or two (72) e.g.
70	rs3486032	0	1359
70	rs3486033	0	1362
70	rs3486034	0	3261
71	rs3486035	0	3948
71	rs3486036	0	3961
71	rs3486037	0	3967
72	rs3486038	0	1355
72	rs3486039	0	1361
73	rs3486040	0	1859
74	rs3486041	0	388
74	rs3486042	0	389
74	rs3486043	0	1272
74	rs3486044	0	1542
74	rs3486045	0	1543
74	rs3486046	0	1626
74	rs3486047	0	2258
74	rs3486048	0	2277
GONE will not be able to make chromosome analyses with this.
To start, I suggest to use only scaffolds with a large number of SNPs.
Armando.

**Comment by andrewSharo** [comment]
Dear Armando,

Thanks for your rapid response! You're right, many of these "chromosomes" are tiny. However, when I modify my plink files to contain just the first 10 chromosomes (which all have at least 960 snps or more) I still get the same error. I'm attaching my ped and map files as a single zip file. These files contain just the first 10 chromosomes.
[all60GenMapGPCFixed10.zip](https://github.com/esrud/GONE/files/14213259/all60GenMapGPCFixed10.zip)

Andrew

**Comment by armando-caballero** [comment]
In the ped file each individual must have -9 before the genotypes:
3 GPC1_BN98 0 0 0 -9 
rather than 
3 GPC1_BN98 0 0 0 1 
Please see the readme and tutorial.
Armando.

**Comment by andrewSharo** [comment]
Thanks, that fixed the issue!

**Comment by kiran-lee** [comment]
Hi @armando-caballero ,
I encounter the same error message using my input files but can run the example successfully. I have subsetted 100,000 SNPs across 28 chromosomes but have adapted the INPUT_PARAMETERS_FILE to include the first 10 chromosomes only (each chromosome has >3000 SNPs). The .ped and .map files appear to be consistent with the format in your user guide. The number of SNPs in the .map file matches that per sample in the .ped file. 
Do you have any other suggestions?
Kiran
[goneinput.ped.zip](https://github.com/user-attachments/files/17257405/goneinput.ped.zip)
[goneinput.map.zip](https://github.com/user-attachments/files/17257407/goneinput.map.zip)

**Comment by armando-caballero** [comment]
The map file has chromosome 21 after chromosome 1. 

1	chr1:119497083	0	119497083
1	chr1:119497366	0	119497366
1	chr1:119497745	0	119497745
1	chr1:119501718	0	119501718
21	chr21:119419	0	119419
21	chr21:124258	0	124258
21	chr21:294871	0	294871
21	chr21:295250	0	295250

The chromosomes must be in order: 1, 2, 3, ...

**Comment by Chen-Kunhao** [comment]
Dear Armando,
I encountered this issue while running Gone as well. Here is my file; I’d appreciate it if you could take a look and see what might be causing

[Gone.zip](https://github.com/user-attachments/files/27788464/Gone.zip)

**Comment by armando-caballero** [comment]
You have only two individuals in your ped file. These are too few to get any reliable estimate.
Best wishes,
Armando.

**Comment by Chen-Kunhao** [comment]
Running GONE
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
  Error opening file outfileLD_TEMP/outfileLD_1_GONE_Nebest
 END OF ALL PROCESSES
GONE run took 0 seconds
END OF ANALYSES
mv: cannot stat 'outfileLD_Ne_estimates': No such file or directory
mv: cannot stat 'outfileLD_d2_sample': No such file or directory

Hello, may I ask whether the situation above occurred simply because the sample size was too small? My file itself should be fine, shouldn't it?

**Comment by armando-caballero** [comment]
Yes, I ran GONE and could not finish, but GONE2 did it. Try that.
With the option -x (structure), I got this:

# Estimate of historical Ne using observed LD  of different recombination bis. This is an
# extension to a subdivided population model of the Hayes et al. (2003) approach and
# should be considered an approximate trend.
#
# Number of subpopulations:
2
# Fst:
0.44224343
# Migration rate:
0.00146158
#
# Rec_rate_bin	generation	N_T_metapop	Ne_metapop	dÂ²_metapop
0.50000	1	94.95	170.24	0.00874256

You may also try currentNe2. But n=2 is too little

Armando.
Armando.

**Comment by Chen-Kunhao** [comment]
Hello, thank you very much for your help. Based on your advice, I increased the sample size to 10 individuals, but it seems I still cannot run the GONE analysis. The following error appears. Is it still because the sample size is too small?

Error log:



ckh@manager:~/gone_analysis/GONE-master/Linux/gone_test$ bash script_GONE.sh all
DIVIDE .ped AND .map FILES IN CHROMOSOMES
RUNNING ANALYSIS OF CHROMOSOMES ...
xargs: bash: terminated by signal 11
CHROMOSOME ANALYSES took 0 seconds
cat: outfileLD1: No such file or directory
sed: cannot read outfileLD1: No such file or directory
cat: parameters1: No such file or directory
cat: outfileLD2: No such file or directory
sed: cannot read outfileLD2: No such file or directory
cat: parameters2: No such file or directory
cat: outfileLD3: No such file or directory
sed: cannot read outfileLD3: No such file or directory
cat: parameters3: No such file or directory
cat: outfileLD4: No such file or directory
sed: cannot read outfileLD4: No such file or directory
cat: parameters4: No such file or directory
cat: outfileLD5: No such file or directory
sed: cannot read outfileLD5: No such file or directory
cat: parameters5: No such file or directory
cat: outfileLD6: No such file or directory
sed: cannot read outfileLD6: No such file or directory
cat: parameters6: No such file or directory
cat: outfileLD7: No such file or directory
sed: cannot read outfileLD7: No such file or directory
cat: parameters7: No such file or directory
cat: outfileLD8: No such file or directory
sed: cannot read outfileLD8: No such file or directory
cat: parameters8: No such file or directory
cat: outfileLD9: No such file or directory
sed: cannot read outfileLD9: No such file or directory
cat: parameters9: No such file or directory
cat: outfileLD10: No such file or directory
sed: cannot read outfileLD10: No such file or directory
cat: parameters10: No such file or directory
cat: outfileLD11: No such file or directory
sed: cannot read outfileLD11: No such file or directory
cat: parameters11: No such file or directory
cat: outfileLD12: No such file or directory
sed: cannot read outfileLD12: No such file or directory
cat: parameters12: No such file or directory
rm: cannot remove 'parameters*': No such file or directory
Running GONE
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
 Format error in file outfileLD
  Error opening file outfileLD_TEMP/outfileLD_1_GONE_Nebest
 END OF ALL PROCESSES
GONE run took 0 seconds
END OF ANALYSES
mv: cannot stat 'outfileLD_Ne_estimates': No such file or directory
mv: cannot stat 'outfileLD_d2_sample': No such file or directory

[gone.zip](https://github.com/user-attachments/files/27854283/gone.zip)

**Comment by Chen-Kunhao** [comment]
May I ask, generally, how many samples are recommended as a minimum?

**Comment by armando-caballero** [comment]
Your data runs well if you reduce the number of SNPs to a reasonable number. You do not need one million SNPs and that takes a long tine. I took 100,000 SNPs at random with plink (--thin-count option) and GONE, GONE2 and currentNe2 all run well. But your results are very strange because the Fis value is 0.65. A huge excess of homozygotes. The average heterzygosity is only 0.1.
Best wshes,
Armando
