### ISSUE TITLE
Example does not work?

### ISSUE THREAD

**Issue by jydu** [esrud/GONE#5]
Hi,

I just ran script_GONE.sh example in the MacOS directory, and I get the error message "Too few bins". Any idea of what I could be doing wrong?

Best,

Julien.

**Comment by esrud** [comment]
Hi Julien,

please, could you try to compile the programs for the particular version of your operating system?

OSX will not be supported in future GONE versions. We recommend you to use Linux version whenever is possible.

Best,

ENrique

**Comment by jydu** [comment]
Hi Enrique,

Compiling the code did not solve the issue. I will try on Linux!

Best,

Julien.

**Comment by jydu** [comment]
Dear Enrique,

The example works on Linux. However, I failed to run the software on my own data. I have the impression the issue comes from my PLINK files. It is my understanding that PED files have genotypes of the form "X Y", where X and Y are the two alleles separated by a space character, while all genotypes are separated by a tabulation. I have the impression the example PLINK files follow a different format, is that correct? Does GONE expect a particular format for the PLINK input files?
If I am correct, GONE uses the last chr number as the total number of chromosomes. This only works, however, if chromosomes are numeric, sorted, and all present in the dataset, right?
Finally, may I ask what "pseudohaploids" are? Is it to account for the fact that PLINK encodes haploids as homozygotes?

Many thanks in advance for your help,

Julien.

**Comment by esrud** [comment]
Right Julien, version 1 of GONE only admits space chars to separate items in ped and map files. PLINK format considers both spaces and tabs. Also, the labels of chromosomes in map files must be ordinal numbers starting by 1 for the first chromosome. We are working in a new version that will consider more variations in formats.

The term pseudohaploid refers to a particular type of data resulting mainly from the sequencing of ancient DNA: A single random base is drawn from heterozygotes sites so individuals are represented as haploid genomes. Although the method leads to a partial loss of information, it is possible to calculate correlations between SNPs and to estimate historical Ne from those data.

Best,

Enrique

**Comment by jydu** [comment]
Dear Enrique,

Thank you for your answer! I could get it to work by using spaces only and -9 instead of 0 for the missing phenotype.
One last question: my data is actually haploid (there is recombination, but the haploid phase was sequenced). It is therefore encoded as homozygotes in PLINK. How is this affecting the results of GONE? Is there a way to tell GONE to only use the first allele? 

Many thanks again,

Julien.

**Comment by esrud** [comment]
Big problem. Gone is not designed to work with haploids. In order to work around this limitation you have to:

1- Group individuals in pairs and think of these pairs as if they were “diploids”. You can do the pairings in any order, no need of randomization. Obviously the haploid sample number must be an even number and, if not, you will have to eliminate one individual.

2- Build a ped file with those “diploids”.

3-  Set the variable PHASE=1 in the INPUT_PARAMETERS_FILE and run Gone (the phase is known in your “diploids”).

4- The effective number of haploids will be twice the number of the Ne historical series in the output.

Certainly it would be feasible to modify the program in order to consider haploids and I’ll do it. Please, could you tell me the species.

Thanks,

ENrique

**Comment by jydu** [comment]
Dear Enrique,

Pulling haploid individuals into diploids is certainly possible, I will give it a try. I am studying several fungal species, for which the haploid phase is easier to sequence than the diploid one. The dataset I am playing with at the moment is one from the yeast Saccharomyces cerevisiae.

Best,

Julien.
